// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LD.EntitiesLD;

public partial class ADDITIONAL_ORGANIZATION_INFORMATION
{
    public long ID_ORGANIZATION { get; set; }

    public long ID_ORGANIZATION_BODEGA { get; set; }

    public int? ID_SERVICE_CLIENT { get; set; }

    public DateTime? DATE_CREATED { get; set; }

    public DateTime? DATE_UPDATE { get; set; }

    public virtual ICollection<CONTACTS> CONTACTS { get; set; } = new List<CONTACTS>();
}