// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LD.EntitiesLD;

public partial class ADDITIONAL_USER_INFORMATION
{
    public int ID_USER { get; set; }

    public int ID_USER_BLU { get; set; }

    public string ID_USER_SF { get; set; }

    public string ID_USER_CW { get; set; }

    public int? ID_COMPANY { get; set; }

    public string BRANCH { get; set; }

    public bool? CHANGE_COUNTRY { get; set; }

    public string POSITION { get; set; }

    public int? DEFAULT_ROL { get; set; }

    public DateTime? DATE_CREATED { get; set; }

    public DateTime? DATE_UPDATE { get; set; }

    public virtual COMPANIES ID_COMPANYNavigation { get; set; }
}