// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LD.EntitiesLD;

public partial class ALARMS
{
    public int ID_ALARM { get; set; }

    public string NAME { get; set; }

    public string DESCRIPTION { get; set; }

    public string EVENTCODE { get; set; }

    public bool SHOW_CALENDAR { get; set; }

    public DateTime? LAST_TIME_EXECUTE { get; set; }

    public DateTime? NEXT_DATE_EXECUTE { get; set; }

    public bool ACTIVE { get; set; }
}