// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LD.EntitiesLD;

public partial class COMPANIES
{
    public int ID_COMPANY { get; set; }

    public string NAME { get; set; }

    public string CODE { get; set; }

    public string ADDRESS { get; set; }

    public string PHONE { get; set; }

    public virtual ICollection<ADDITIONAL_USER_INFORMATION> ADDITIONAL_USER_INFORMATION { get; set; } = new List<ADDITIONAL_USER_INFORMATION>();
}