// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LD.EntitiesLD;

public partial class CONTACTS
{
    public long ID_CONTACT { get; set; }

    public long ID_ORGANIZATION_BODEGA { get; set; }

    public string NAME_CONTACT { get; set; }

    public string LASTNAME_CONTACT { get; set; }

    public string EMAIL_CONTACT { get; set; }

    public string PHONE_CONTACT { get; set; }

    public DateTime? DATE_CREATED { get; set; }

    public DateTime? DATE_UPDATE { get; set; }

    public virtual ADDITIONAL_ORGANIZATION_INFORMATION ID_ORGANIZATION_BODEGANavigation { get; set; }
}