// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LD.EntitiesLD;

public partial class CONTACT_ALARMS
{
    public int ID_CONTACT_ALARMS { get; set; }

    public int ID_ORGANIZATION { get; set; }

    public long ID_CONTACT { get; set; }

    public string EVENTCODE { get; set; }

    public bool LUNES { get; set; }

    public bool MARTES { get; set; }

    public bool MIERCOLES { get; set; }

    public bool JUEVES { get; set; }

    public bool VIERNES { get; set; }

    public bool SABADO { get; set; }

    public bool DOMINGO { get; set; }

    public string DOCUMENTTYPE { get; set; }
}