// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LD.EntitiesLD;

public partial class INSTRUCTIVE
{
    public int ID_INSTRUCTIVE { get; set; }

    public string DESCRIPTION { get; set; }

    public string ROLES { get; set; }

    public string ATTACHED { get; set; }

    public bool IS_ACTIVE { get; set; }

    public string TOPIC { get; set; }

    public string COMPANIES { get; set; }
}