// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LD.EntitiesLD;

public partial class STATUS_SEND_TYPE
{
    public int ID_STATUS_SEND { get; set; }

    public string DESCRIPTION { get; set; }

    public virtual ICollection<STATUS_ALARMS_LOG> STATUS_ALARMS_LOG { get; set; } = new List<STATUS_ALARMS_LOG>();
}