// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LD.EntitiesLD;

public partial class SYSTEM_PARAMS
{
    public int ID_SYSTEM_PARAMS { get; set; }

    public string DESCRIPTION { get; set; }

    public string VALUE { get; set; }

    public string OBSERVATIONS { get; set; }

    public string ACTIVE { get; set; }

    public bool? UPDATABLE { get; set; }
}