// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LD.EntitiesGB;

public partial class CGW_GEN_SalesPerson
{
    public int intSalesPersonID { get; set; }

    public string codeCW { get; set; }

    public string charName { get; set; }

    public string charAddress { get; set; }

    public string charCity { get; set; }

    public string charState { get; set; }

    public string charZipCode { get; set; }

    public string charCountry { get; set; }

    public string charContact { get; set; }

    public string charPhone1 { get; set; }

    public string charPhone2 { get; set; }

    public string charFax { get; set; }

    public string charEmail { get; set; }

    public string charCode { get; set; }

    public string charAccountNumber { get; set; }

    public string charDateFrom { get; set; }

    public string charDateTo { get; set; }

    public string charStatus { get; set; }

    public int? intVendorsID { get; set; }

    public int? intEmployeeID { get; set; }

    public int? intTerritoryID { get; set; }

    public string charMiddleName { get; set; }

    public string charLastName { get; set; }

    public int intPercent { get; set; }

    public short intIFInternal { get; set; }

    public string charTitle { get; set; }

    public string charType { get; set; }

    public string charInterCompanyCode { get; set; }
}