// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LD.EntitiesGB;

public partial class GB_modulePermission
{
    public int modPer_id { get; set; }

    public int? mod_id { get; set; }

    public int domVal_permitType { get; set; }

    public virtual GB_module mod { get; set; }
}