// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LD.EntitiesGB;

public partial class GB_module
{
    public int mod_id { get; set; }

    public string mod_name { get; set; }

    public string mod_path { get; set; }

    public string mod_params { get; set; }

    public bool? mod_chargeMode { get; set; }

    public bool? mod_private { get; set; }

    public bool? mod_active { get; set; }

    public int? domVal_moduleType { get; set; }

    public int? mod_fatherId { get; set; }

    public int mod_position { get; set; }

    public string mod_initials { get; set; }

    public string mod_model { get; set; }

    public bool? mod_share { get; set; }

    public string mod_adapter { get; set; }

    public virtual ICollection<GB_modulePermission> GB_modulePermission { get; set; } = new List<GB_modulePermission>();

    public virtual ICollection<GB_userModule> GB_userModule { get; set; } = new List<GB_userModule>();

    public virtual ICollection<GB_module> Inversemod_father { get; set; } = new List<GB_module>();

    public virtual GB_module mod_father { get; set; }
}