// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LD.EntitiesGB;

public partial class GB_rolePermission
{
    public int rol_id { get; set; }

    public int modPer_id { get; set; }

    public virtual GB_role rol { get; set; }
}