// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LD.EntitiesGB;

public partial class GB_role
{
    public int rol_id { get; set; }

    public string rol_name { get; set; }

    public string rol_initials { get; set; }

    public string rol_description { get; set; }

    public string sistema { get; set; }

    public virtual ICollection<GB_rolePermission> GB_rolePermission { get; set; } = new List<GB_rolePermission>();

    public virtual ICollection<GB_userRole> GB_userRole { get; set; } = new List<GB_userRole>();
}