// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LD.EntitiesGB;

public partial class GB_userModule
{
    public int useMod_id { get; set; }

    public int? mod_id { get; set; }

    public int? use_id { get; set; }

    public bool? useMod_last_view { get; set; }

    public virtual GB_module mod { get; set; }

    public virtual GB_user use { get; set; }
}