// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LD.EntitiesGB;

public partial class GB_userRole
{
    public int use_id { get; set; }

    public int rol_id { get; set; }

    public bool useRol_default { get; set; }

    public virtual GB_role rol { get; set; }

    public virtual GB_user use { get; set; }
}