// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LD.EntitiesGB;

public partial class GB_user
{
    public int use_id { get; set; }

    public string use_user { get; set; }

    public string use_password { get; set; }

    public string use_name { get; set; }

    public string use_lastName { get; set; }

    public int? domVal_language { get; set; }

    public int? use_partner { get; set; }

    public string use_mail { get; set; }

    public bool? use_active { get; set; }

    public int? use_profile { get; set; }

    public int? use_identification { get; set; }

    public int? braOff_id { get; set; }

    public int? domVal_identificationType { get; set; }

    public int? use_extension { get; set; }

    public bool? use_visibleExtension { get; set; }

    public bool? use_LDAP { get; set; }

    public int? domVal_question { get; set; }

    public string use_answer { get; set; }

    public DateTime? use_createDate { get; set; }

    public DateTime? use_editDate { get; set; }

    public DateTime? use_passwordDate { get; set; }

    public string use_alias { get; set; }

    public string use_cellNumber { get; set; }

    public string use_business_unit { get; set; }

    public string use_departament { get; set; }

    public string use_city { get; set; }

    public string use_charge { get; set; }

    public int? use_dashboard { get; set; }

    public int? use_country { get; set; }

    public virtual ICollection<GB_userModule> GB_userModule { get; set; } = new List<GB_userModule>();

    public virtual ICollection<GB_userRole> GB_userRole { get; set; } = new List<GB_userRole>();
}