// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using LD.EntitiesCotizador;
using Microsoft.EntityFrameworkCore;

namespace LD.DataCotizador;

public partial class BPCotizadorContext : DbContext
{
    public BPCotizadorContext(DbContextOptions<BPCotizadorContext> options)
        : base(options)
    {
    }

    public virtual DbSet<CUSTOMERS> CUSTOMERS { get; set; }

    public virtual DbSet<SALES_SUPPORTS> SALES_SUPPORTS { get; set; }

    public virtual DbSet<USERS_APPS> USERS_APPS { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<CUSTOMERS>(entity =>
        {
            entity.HasKey(e => e.ID_CUSTOMER);

            entity.Property(e => e.ADDRESS).HasMaxLength(150);
            entity.Property(e => e.ATTENTION)
                .HasMaxLength(150)
                .IsUnicode(false);
            entity.Property(e => e.CONTACT_EMAIL)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.CONTACT_NAME)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.CONTACT_PHONE)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.COUNTRY).HasMaxLength(150);
            entity.Property(e => e.CW_CODE)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ID_SALESFORCE).HasMaxLength(150);
            entity.Property(e => e.ID_SALES_PERSON_SF).HasMaxLength(150);
            entity.Property(e => e.NAME).HasMaxLength(150);
            entity.Property(e => e.PHONE)
                .HasMaxLength(60)
                .IsUnicode(false);
            entity.Property(e => e.POSITION_SALES_PERSON).HasMaxLength(400);
            entity.Property(e => e.REG_NUMBER).HasMaxLength(150);
        });

        modelBuilder.Entity<SALES_SUPPORTS>(entity =>
        {
            entity.HasOne(d => d.ID_COMERCIALNavigation).WithMany(p => p.SALES_SUPPORTSID_COMERCIALNavigation)
                .HasForeignKey(d => d.ID_COMERCIAL)
                .HasConstraintName("FK_SALES_SUPPORTS_USERS_APPS");

            entity.HasOne(d => d.ID_SALE_SUPPORTNavigation).WithMany(p => p.SALES_SUPPORTSID_SALE_SUPPORTNavigation)
                .HasForeignKey(d => d.ID_SALE_SUPPORT)
                .HasConstraintName("FK_SALES_SUPPORTS_USERS_APPS1");
        });

        modelBuilder.Entity<USERS_APPS>(entity =>
        {
            entity.HasKey(e => e.ID_USER);

            entity.Property(e => e.ID_USER).ValueGeneratedNever();
            entity.Property(e => e.BRANCH)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.DOCUMENT_NUMBER)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.EMAIL)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.FIRST_NAME)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ID_USER_CW)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ID_USER_SF).HasMaxLength(150);
            entity.Property(e => e.LAST_NAME)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.POSITION)
                .HasMaxLength(150)
                .IsUnicode(false);
            entity.Property(e => e.USERNAME)
                .HasMaxLength(150)
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}