// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using LD.EntitiesLD;
using Microsoft.EntityFrameworkCore;

namespace LD.DataLD;

public partial class ListaDistribucionContext : DbContext
{
    public ListaDistribucionContext(DbContextOptions<ListaDistribucionContext> options)
        : base(options)
    {
    }

    public virtual DbSet<ACTIVITY_LOG> ACTIVITY_LOG { get; set; }

    public virtual DbSet<ADDITIONAL_ORGANIZATION_INFORMATION> ADDITIONAL_ORGANIZATION_INFORMATION { get; set; }

    public virtual DbSet<ADDITIONAL_USER_INFORMATION> ADDITIONAL_USER_INFORMATION { get; set; }

    public virtual DbSet<ALARMS> ALARMS { get; set; }

    public virtual DbSet<COMPANIES> COMPANIES { get; set; }

    public virtual DbSet<CONTACTS> CONTACTS { get; set; }
    public virtual DbSet<CONTACT_ALARMS> CONTACT_ALARMS { get; set; }

    public virtual DbSet<INSTRUCTIVE> INSTRUCTIVE { get; set; }

    public virtual DbSet<STATUS_ALARMS_LOG> STATUS_ALARMS_LOG { get; set; }

    public virtual DbSet<STATUS_SEND_TYPE> STATUS_SEND_TYPE { get; set; }

    public virtual DbSet<SYSTEM_PARAMS> SYSTEM_PARAMS { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ACTIVITY_LOG>(entity =>
        {
            entity.HasKey(e => e.ID_LOG).HasName("PK_Activity_Log");

            entity.Property(e => e.DATE_OPERATION).HasColumnType("datetime");
            entity.Property(e => e.NEW_VALUE)
                .HasMaxLength(150)
                .IsUnicode(false);
            entity.Property(e => e.OLD_VALUE)
                .HasMaxLength(150)
                .IsUnicode(false);
            entity.Property(e => e.OPERATION)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
        });

        modelBuilder.Entity<ADDITIONAL_ORGANIZATION_INFORMATION>(entity =>
        {
            entity.HasKey(e => e.ID_ORGANIZATION_BODEGA).HasName("PK_ADDITIONAL_ORGANIZATION_INFORMATION_1");

            entity.Property(e => e.ID_ORGANIZATION_BODEGA).ValueGeneratedNever();
            entity.Property(e => e.DATE_CREATED).HasColumnType("datetime");
            entity.Property(e => e.DATE_UPDATE).HasColumnType("datetime");
            entity.Property(e => e.ID_ORGANIZATION).ValueGeneratedOnAdd();
        });

        modelBuilder.Entity<ADDITIONAL_USER_INFORMATION>(entity =>
        {
            entity.HasKey(e => e.ID_USER);

            entity.Property(e => e.BRANCH)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.DATE_CREATED).HasColumnType("datetime");
            entity.Property(e => e.DATE_UPDATE).HasColumnType("datetime");
            entity.Property(e => e.ID_USER_CW)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ID_USER_SF)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.POSITION)
                .HasMaxLength(150)
                .IsUnicode(false);

            entity.HasOne(d => d.ID_COMPANYNavigation).WithMany(p => p.ADDITIONAL_USER_INFORMATION)
                .HasForeignKey(d => d.ID_COMPANY)
                .HasConstraintName("FK_ADDITIONAL_USER_INFORMATION_COMPANIES");
        });

        modelBuilder.Entity<ALARMS>(entity =>
        {
            entity.HasKey(e => e.ID_ALARM).HasName("PK_ALARMS_1");

            entity.Property(e => e.DESCRIPTION)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.EVENTCODE)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.NAME)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<COMPANIES>(entity =>
        {
            entity.HasKey(e => e.ID_COMPANY).HasName("PK_COUNTRIES");

            entity.Property(e => e.ADDRESS).HasMaxLength(150);
            entity.Property(e => e.CODE)
                .IsRequired()
                .HasMaxLength(3)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.NAME)
                .IsRequired()
                .HasMaxLength(150)
                .IsUnicode(false);
            entity.Property(e => e.PHONE).HasMaxLength(150);
        });

        modelBuilder.Entity<CONTACTS>(entity =>
        {
            entity.HasKey(e => e.ID_CONTACT).HasName("PK_Contacts");

            entity.Property(e => e.DATE_CREATED).HasColumnType("datetime");
            entity.Property(e => e.DATE_UPDATE).HasColumnType("datetime");
            entity.Property(e => e.EMAIL_CONTACT)
                .IsRequired()
                .HasMaxLength(80)
                .IsUnicode(false);
            entity.Property(e => e.LASTNAME_CONTACT)
                .HasMaxLength(150)
                .IsUnicode(false);
            entity.Property(e => e.NAME_CONTACT)
                .IsRequired()
                .HasMaxLength(150)
                .IsUnicode(false);
            entity.Property(e => e.PHONE_CONTACT)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.ID_ORGANIZATION_BODEGANavigation).WithMany(p => p.CONTACTS)
                .HasForeignKey(d => d.ID_ORGANIZATION_BODEGA)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__CONTACTS__ID_ORG__31EC6D26");
        });

        modelBuilder.Entity<CONTACT_ALARMS>(entity =>
        {
            entity.HasKey(e => e.ID_CONTACT_ALARMS).HasName("PK_ALARMS");

            entity.Property(e => e.DOCUMENTTYPE)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.EVENTCODE)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<INSTRUCTIVE>(entity =>
        {
            entity.HasKey(e => e.ID_INSTRUCTIVE);

            entity.Property(e => e.COMPANIES).HasMaxLength(500);
            entity.Property(e => e.DESCRIPTION).HasMaxLength(500);
            entity.Property(e => e.ROLES).HasMaxLength(500);
            entity.Property(e => e.TOPIC).HasMaxLength(250);
        });

        modelBuilder.Entity<STATUS_ALARMS_LOG>(entity =>
        {
            entity.HasKey(e => e.ID_STATUS);

            entity.Property(e => e.DATE_CREATED).HasColumnType("datetime");
            entity.Property(e => e.MESSAGE_ERROR).IsUnicode(false);
            entity.Property(e => e.MESSAGE_SEND).IsUnicode(false);
            entity.Property(e => e.RECIPIENTS)
                .HasMaxLength(250)
                .IsUnicode(false);

            entity.HasOne(d => d.ID_STATUS_SENDNavigation).WithMany(p => p.STATUS_ALARMS_LOG)
                .HasForeignKey(d => d.ID_STATUS_SEND)
                .HasConstraintName("FK__STATUS_AL__ID_ST__3B75D760");
        });

        modelBuilder.Entity<STATUS_SEND_TYPE>(entity =>
        {
            entity.HasKey(e => e.ID_STATUS_SEND);

            entity.Property(e => e.DESCRIPTION)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<SYSTEM_PARAMS>(entity =>
        {
            entity.HasKey(e => e.ID_SYSTEM_PARAMS).HasName("PK_PARAMETRO_SISTEMA");

            entity.Property(e => e.ACTIVE).HasMaxLength(1);
            entity.Property(e => e.DESCRIPTION).HasMaxLength(250);
            entity.Property(e => e.OBSERVATIONS).HasColumnType("text");
            entity.Property(e => e.VALUE).HasMaxLength(250);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}