// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LD.EntitiesCotizador;

public partial class CUSTOMERS
{
    public long ID_CUSTOMER { get; set; }

    public string ID_SALESFORCE { get; set; }

    public string NAME { get; set; }

    public string ATTENTION { get; set; }

    public string REG_NUMBER { get; set; }

    public string PHONE { get; set; }

    public string ADDRESS { get; set; }

    public string COUNTRY { get; set; }

    public string ID_SALES_PERSON_SF { get; set; }

    public string POSITION_SALES_PERSON { get; set; }

    public bool? IS_AGENT { get; set; }

    public string CW_CODE { get; set; }

    public string CONTACT_NAME { get; set; }

    public string CONTACT_PHONE { get; set; }

    public string CONTACT_EMAIL { get; set; }
}