// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LD.EntitiesCotizador;

public partial class SALES_SUPPORTS
{
    public int ID { get; set; }

    public int? ID_COMERCIAL { get; set; }

    public int? ID_SALE_SUPPORT { get; set; }

    public virtual USERS_APPS ID_COMERCIALNavigation { get; set; }

    public virtual USERS_APPS ID_SALE_SUPPORTNavigation { get; set; }
}